import type { LogoConfig, Rarity } from "@/lib/logoGenerator";

// Daily limits and tries
export const TRIES_PER_DAY = 3;
export const BONUS_TRIES_FOR_MASTER = 1;

// Word list for random generation
export const RANDOM_WORDS = [
  "Arcade",
  "Pixel",
  "Forge",
  "Neon",
  "Crt",
  "Quest",
  "Byte",
  "Retro",
  "Glitch",
  "Tron",
  "Blade Runner",
  "Alien",
  "Predator",
  "The Matrix",
  "Dune",
  "Star Trek",
  "Doctor Who",
  "The Expanse",
  "Battlestar",
  "Neon Genesis",
  "Asteroids",
  "Galaga",
  "Centipede",
  "Tempest",
  "Defender",
  "Gauntlet",
  "Frogger",
  "Dig Dug",
  "Pac-Man",
  "Space Invaders",
  "Metroid",
  "Mega Man",
  "Contra",
  "OutRun",
  "Robotron",
  "Qbert",
  "Arkanoid",
  "Bubble Bobble",
  "R-Type",
  "Gradius",
  "Tekken",
  "Street Fighter",
  "Mortal Kombat",
  "Double Dragon",
  "Golden Axe",
  "After Burner",
  "Ms Pac-Man",
  "Star Wars",
  "The Fifth Element",
  "Terminator",
  "RoboCop",
  "Akira",
  "Ghost in the Shell",
  "Cowboy Bebop",
  "Firefly",
  "Stargate",
  "X-Files",
  "Westworld",
  "Black Mirror",
  "Altered Carbon",
  "Apple",
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Netflix",
  "Nvidia",
  "Intel",
  "AMD",
  "Samsung",
  "Sony",
  "Tesla",
  "OpenAI",
  "IBM",
  "Oracle",
  "Bitcoin",
  "Ethereum",
  "Solana",
  "Cardano",
  "Polkadot",
  "Litecoin",
  "Dogecoin",
  "Shiba Inu",
  "Avalanche",
  "Chainlink",
  "Uniswap",
  "Tether",
  "USD Coin",
  "Ripple",
  "Stellar",
  "Monero",
  "Aave",
  "Cosmos",
  "Algorand",
  "Polygon",
  "Toncoin",
  "NEAR",
  "Filecoin",
  "Arbitrum",
  "Base",
  "Base Chain",
  "Basetown",
  "Coinbase",
  "L2",
  "Mainnet",
  "Testnet",
  "Onchain",
  "Onchain Summer",
  "DeFi",
  "NFT",
  "GM",
  "WAGMI",
  "NGMI",
  "Fren",
  "Degens",
  "Ape",
  "Airdrop",
  "Mint",
  "HODL",
  "FOMO",
  "FUD",
  "Alpha",
  "Beta",
  "Liquid",
  "Liquidity",
  "Gas",
  "Gwei",
  "Bridge",
  "Yield",
  "Staking",
  "Restake",
  "Farcaster",
  "Warpcast",
  "Caster",
  "Cast",
  "Recap",
  "Channel",
  "Frames",
  "Frame",
  "Moxie",
  "Neynar",
  "FIDs",
  "Username",
  "Profile",
  "Mint Party",
  "Basecamp",
  "Onchain ID",
  "Verified",
  "Tipping",
  "Nouns",
  "Farcaster Hub",
] as const;

// Preset configurations
export const PRESETS: Array<{
  key: string;
  label: string;
  config: Partial<LogoConfig>;
}> = [
  {
    key: "neon-synthwave",
    label: "⚡ Neon Synthwave",
    config: {
      backgroundStyle: "vaporwave-sky",
      frameStyle: "arcade-bezel",
      colorSystem: "Vaporwave",
      compositionMode: "centered",
    },
  },
  {
    key: "cyberpunk-retro",
    label: "🎮 Cyberpunk Retro",
    config: {
      backgroundStyle: "crt-scanlines",
      frameStyle: "trading-card",
      colorSystem: "Classic",
      compositionMode: "vertical-stacked",
    },
  },
  {
    key: "monochrome-minimal",
    label: "⬛ Monochrome Minimal",
    config: {
      backgroundStyle: "grid-horizon",
      frameStyle: "none",
      colorSystem: "GameBoy",
      compositionMode: "centered",
    },
  },
];

// Rarity levels
export const RARITY_OPTIONS: Rarity[] = ["COMMON", "RARE", "EPIC", "LEGENDARY"];

// Color swatches for presets
export const PRESET_SWATCHES: Record<string, string[]> = {
  "neon-synthwave": ["#ff006e", "#8338ec", "#3a86ff", "#ffbe0b"],
  "cyberpunk-retro": ["#00ff00", "#ff00ff", "#ffff00", "#00ffff"],
  "monochrome-minimal": ["#000000", "#ffffff", "#808080"],
};

// Challenge prompts
export const ALL_CHALLENGE_PROMPTS = [
  { name: "Nike", description: "Generate a logo for Nike" },
  { name: "Adidas", description: "Generate a logo for Adidas" },
  { name: "Apple", description: "Generate a logo for Apple" },
  { name: "Tesla", description: "Generate a logo for Tesla" },
  { name: "Gucci", description: "Generate a logo for Gucci" },
  { name: "Spotify", description: "Generate a logo for Spotify" },
  { name: "Meta", description: "Generate a logo for Meta" },
  { name: "Sony", description: "Generate a logo for Sony" },
  { name: "Uber", description: "Generate a logo for Uber" },
  { name: "BMW", description: "Generate a logo for BMW" },
  { name: "Dior", description: "Generate a logo for Dior" },
  { name: "Amazon", description: "Generate a logo for Amazon" },
  { name: "Nintendo", description: "Generate a logo for Nintendo" },
  { name: "Arcade Nova", description: "Generate a logo for Arcade Nova" },
  { name: "Pixel Forge", description: "Generate a logo for Pixel Forge" },
  { name: "Neon Circuit", description: "Generate a logo for Neon Circuit" },
  { name: "Retro Pulse", description: "Generate a logo for Retro Pulse" },
  {
    name: "Synthwave Studios",
    description: "Generate a logo for Synthwave Studios",
  },
  { name: "Cosmic Arcade", description: "Generate a logo for Cosmic Arcade" },
  { name: "Voxel Labs", description: "Generate a logo for Voxel Labs" },
  { name: "Quantum Byte", description: "Generate a logo for Quantum Byte" },
  { name: "Laser Lotus", description: "Generate a logo for Laser Lotus" },
  { name: "Turbo Knight", description: "Generate a logo for Turbo Knight" },
  { name: "Nova Drift", description: "Generate a logo for Nova Drift" },
  { name: "Astro Guild", description: "Generate a logo for Astro Guild" },
  {
    name: "Moonlit Circuit",
    description: "Generate a logo for Moonlit Circuit",
  },
  { name: "Solar Ember", description: "Generate a logo for Solar Ember" },
  {
    name: "Starlight Forge",
    description: "Generate a logo for Starlight Forge",
  },
  { name: "Night Runner", description: "Generate a logo for Night Runner" },
  { name: "Crimson Alley", description: "Generate a logo for Crimson Alley" },
  { name: "Blue Nebula", description: "Generate a logo for Blue Nebula" },
  { name: "Echo City", description: "Generate a logo for Echo City" },
  { name: "Magnetic Field", description: "Generate a logo for Magnetic Field" },
  { name: "Ghost Circuit", description: "Generate a logo for Ghost Circuit" },
  { name: "Holo Garden", description: "Generate a logo for Holo Garden" },
  { name: "Cyber Meadow", description: "Generate a logo for Cyber Meadow" },
  { name: "Vapor Harbor", description: "Generate a logo for Vapor Harbor" },
  { name: "Aurora Signal", description: "Generate a logo for Aurora Signal" },
  { name: "Thunder Drive", description: "Generate a logo for Thunder Drive" },
  { name: "Sunset Grid", description: "Generate a logo for Sunset Grid" },
  { name: "Plasma Reef", description: "Generate a logo for Plasma Reef" },
  { name: "Byte Bazaar", description: "Generate a logo for Byte Bazaar" },
  { name: "Circuit Atlas", description: "Generate a logo for Circuit Atlas" },
  { name: "Pixel Harbor", description: "Generate a logo for Pixel Harbor" },
  { name: "Cosmo Cartel", description: "Generate a logo for Cosmo Cartel" },
  { name: "Retro Rocket", description: "Generate a logo for Retro Rocket" },
  { name: "Neon Nomad", description: "Generate a logo for Neon Nomad" },
  { name: "Prism Arcade", description: "Generate a logo for Prism Arcade" },
  { name: "Orbital Bloom", description: "Generate a logo for Orbital Bloom" },
  { name: "Glitch Garden", description: "Generate a logo for Glitch Garden" },
  { name: "Zero Gravity", description: "Generate a logo for Zero Gravity" },
  { name: "Pixel Parade", description: "Generate a logo for Pixel Parade" },
  { name: "Lunar Arcade", description: "Generate a logo for Lunar Arcade" },
  { name: "Cobalt Drift", description: "Generate a logo for Cobalt Drift" },
  { name: "Crimson Pixel", description: "Generate a logo for Crimson Pixel" },
  { name: "Hyperwave", description: "Generate a logo for Hyperwave" },
  { name: "Retroverse", description: "Generate a logo for Retroverse" },
  { name: "Spectra Core", description: "Generate a logo for Spectra Core" },
  { name: "Vector Vault", description: "Generate a logo for Vector Vault" },
  { name: "Photon Peak", description: "Generate a logo for Photon Peak" },
  { name: "Glacier Byte", description: "Generate a logo for Glacier Byte" },
  {
    name: "Midnight Arcade",
    description: "Generate a logo for Midnight Arcade",
  },
  { name: "Aurora Arcade", description: "Generate a logo for Aurora Arcade" },
] as const;

// Daily challenge rotation
export const DAILY_PROMPTS = [
  "Meta",
  "Sony",
  "Uber",
  "BMW",
  "Dior",
  "Amazon",
  "Nintendo",
  "Arcade Nova",
  "Pixel Forge",
  "Neon Circuit",
  "Retro Pulse",
  "Synthwave Studios",
  "Cosmic Arcade",
  "Voxel Labs",
  "Quantum Byte",
  "Laser Lotus",
  "Turbo Knight",
  "Nova Drift",
  "Astro Guild",
  "Moonlit Circuit",
  "Solar Ember",
  "Starlight Forge",
  "Night Runner",
  "Echo City",
  "Vapor Harbor",
  "Aurora Signal",
  "Thunder Drive",
  "Sunset Grid",
  "Plasma Reef",
  "Byte Bazaar",
  "Circuit Atlas",
  "Pixel Harbor",
  "Retro Rocket",
  "Neon Nomad",
  "Prism Arcade",
  "Orbital Bloom",
  "Glitch Garden",
  "Zero Gravity",
  "Pixel Parade",
  "Lunar Arcade",
  "Cobalt Drift",
  "Crimson Pixel",
  "Hyperwave",
  "Retroverse",
  "Spectra Core",
  "Vector Vault",
  "Photon Peak",
  "Glacier Byte",
  "Midnight Arcade",
  "Aurora Arcade",
] as const;
